-keep interface com.callstack.reactnativebrownfield.OnJSBundleLoaded { *; }
-keep interface com.callstack.reactnativebrownfield.OnDisplayMetrics { *; }
-keep class com.callstack.reactnativebrownfield.JSBundleTimings { *; }
-keep class com.callstack.reactnativebrownfield.BrownfieldDisplayMetrics { *; }
-keep class com.callstack.reactnativebrownfield.BrownfieldDisplayInterval { *; }
-keep class com.callstack.reactnativebrownfield.BrownfieldThreadMetrics { *; }
-keep class com.callstack.reactnativebrownfield.BrownfieldPerformanceModule { *; }
