name: Setup
description: Setup Node.js and install dependencies

inputs:
  restore-turbo-cache:
    description: 'Whether to restore the Turbo cache'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5 # v6
      with:
        node-version: 'lts/*'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Build packages
      run: yarn build
      shell: bash

    - name: Restore Turbo cache
      if: inputs.restore-turbo-cache == 'true'
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: |
          .turbo
          apps/*/.turbo
          packages/*/.turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('.turbo', '**/.turbo') }}
        restore-keys: |
          ${{ runner.os }}-turbo-
