name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'yarn'

    - name: Cache turbo
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          apps/*/.turbo
          packages/*/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      run: yarn install
      shell: bash
