/**
 * Generates the ReactNativeHostManager helper class for Android
 */

interface HostManagerOptions {
  packageName: string;
}

/**
 * Generates the content for Expo-aware ReactNativeHostManager.kt
 */
export function getExpoHostManagerContent({
  packageName,
}: HostManagerOptions): string {
  return `package ${packageName}

import android.app.Application
import com.callstack.reactnativebrownfield.OnJSBundleLoaded
import com.callstack.reactnativebrownfield.ReactNativeBrownfield
import com.facebook.react.PackageList
import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative

/**
 * ReactNativeHostManager - Entry point for initializing React Native in brownfield apps.
 *
 * This class wraps the react-native-brownfield API to provide a simple interface
 * for native apps to initialize React Native without interacting with RN APIs directly.
 *
 * This version is configured for Expo projects with Expo Modules support.
 *
 * Generated by @callstack/react-native-brownfield
 */
object ReactNativeHostManager {
    fun initialize(application: Application, onJSBundleLoaded: OnJSBundleLoaded? = null) {
        loadReactNative(application)

        ReactNativeBrownfield.initialize(
            application, hashMapOf(
                "mainModuleName" to ".expo/.virtual-metro-entry",
                "packageList" to PackageList(application).packages
            ), onJSBundleLoaded
        )
    }
}
`;
}

/**
 * Helper to generate the host manager file in the project
 */
export function generateReactNativeHostManager(options: HostManagerOptions): {
  path: string;
  content: string;
} {
  const content = getExpoHostManagerContent(options);

  const packagePath = options.packageName.replace(/\./g, '/');

  return {
    path: `src/main/java/${packagePath}/ReactNativeHostManager.kt`,
    content,
  };
}
