[versions]
kotlinJvm = "2.0.21"
ktlint = "12.1.1"
detekt = "1.23.7"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint"}
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}