name: Android road test (selected RN app & AndroidApp)
description: Package the given RN app as AAR, publish to Maven Local, and build the corresponding AndroidApp flavor

inputs:
  flavor:
    description: 'AndroidApp flavor to build (expo or vanilla)'
    required: true

  rn-project-path:
    description: 'Path to the RN project to build'
    required: true

  rn-project-maven-path:
    description: 'Maven path to the RN project, e.g. com/rnapp/brownfieldlib'
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Prepare Android environment
      uses: ./.github/actions/prepare-android

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # == Brownfield Gradle Plugin ==
    - name: Publish Brownfield Gradle Plugin to Maven Local
      run: |
        yarn run brownfield:plugin:publish:local
      shell: bash

    # == RN app ==
    - name: Prebuild Expo app
      if: ${{ inputs.flavor == 'expo' }}
      run: |
        cd ${{ inputs.rn-project-path }}
        yarn run expo prebuild --platform android
      shell: bash

    - name: Patch ExpoApp Android build.gradle for CI
      if: ${{ inputs.flavor == 'expo' }}
      run: |
        cd ${{ inputs.rn-project-path }}
        yarn run brownfield:prepare:android:ci
      shell: bash

    - name: Package AAR with the Brownfield CLI
      run: |
        cd ${{ inputs.rn-project-path }}
        yarn run brownfield:package:android
      shell: bash

    - name: Publish AAR artifact to Maven Local
      run: |
        cd ${{ inputs.rn-project-path }}
        yarn run brownfield:publish:android
      shell: bash

    - name: Verify debug AAR exists in Maven Local
      run: stat ~/.m2/repository/${{ inputs.rn-project-maven-path }}/0.0.1-SNAPSHOT/brownfieldlib-0.0.1-SNAPSHOT-debug.aar
      shell: bash

    - name: Verify release AAR exists in Maven Local
      run: stat ~/.m2/repository/${{ inputs.rn-project-maven-path }}/0.0.1-SNAPSHOT/brownfieldlib-0.0.1-SNAPSHOT-release.aar
      shell: bash

    # == AndroidApp ==

    - name: Build native Android Brownfield app
      run: yarn run build:example:android-consumer:${{ inputs.flavor }}
      shell: bash
