import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = __dirname;
const SKIP_ENV_VAR = 'SKIP_BROWNFIELD_NAVIGATION_CHECK';

const PROTECTED_GENERATED_FILES = [
  'packages/brownfield-navigation/src/NativeBrownfieldNavigation.ts',
  'packages/brownfield-navigation/src/index.ts',
  'packages/brownfield-navigation/lib/commonjs/index.js',
  'packages/brownfield-navigation/lib/module/index.js',
  'packages/brownfield-navigation/lib/typescript/commonjs/src/index.d.ts',
  'packages/brownfield-navigation/lib/typescript/module/src/index.d.ts',
  'packages/brownfield-navigation/ios/BrownfieldNavigationDelegate.swift',
  'packages/brownfield-navigation/ios/BrownfieldNavigationModels.swift',
  'packages/brownfield-navigation/ios/NativeBrownfieldNavigation.mm',
  'packages/brownfield-navigation/android/src/main/java/com/callstack/nativebrownfieldnavigation/BrownfieldNavigationDelegate.kt',
  'packages/brownfield-navigation/android/src/main/java/com/callstack/nativebrownfieldnavigation/BrownfieldNavigationModels.kt',
  'packages/brownfield-navigation/android/src/main/java/com/callstack/nativebrownfieldnavigation/NativeBrownfieldNavigationModule.kt',
];

function readStagedFiles(repoRoot: string): string[] {
  const output = execFileSync(
    'git',
    ['diff', '--cached', '--name-only', '--diff-filter=ACMR'],
    {
      cwd: repoRoot,
      encoding: 'utf8',
    }
  );

  return output
    .split('\n')
    .map((filePath) => filePath.trim())
    .filter(Boolean);
}

function main(): void {
  if (process.env[SKIP_ENV_VAR] === '1') {
    console.log(
      `${SKIP_ENV_VAR}=1 set, skipping brownfield navigation generated file check`
    );
    return;
  }

  const protectedFiles = new Set(PROTECTED_GENERATED_FILES);
  const stagedProtectedFiles = readStagedFiles(REPO_ROOT).filter((filePath) =>
    protectedFiles.has(filePath)
  );

  if (stagedProtectedFiles.length === 0) {
    return;
  }

  console.error(
    [
      'Commit blocked: generated brownfield-navigation files are staged.',
      '',
      'These files are generated by brownfield navigation codegen and should not be committed accidentally:',
      ...stagedProtectedFiles.map((filePath) => `- ${filePath}`),
      '',
      `If this change is intentional, bypass once with: ${SKIP_ENV_VAR}=1 git commit -m "..."`,
    ].join('\n')
  );
  process.exit(1);
}

main();
